routes/admin.php
<?php

Route::group(['prefix' => 'inside', 'as' => 'admin.'], function () {
    Route::group(['prefix' => 'auth'], function () {
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    });

    Route::group(['middleware' => ['auth', 'admin_panel_access']], function () {
        Route::post('ckeditor/upload', 'CkeditorController@upload')->name('ckeditor.upload');

        Route::get('/', 'HomeController@index')->name('home');
        Route::get('/file-manager', 'FilemanagerController@index')->name('fm.index');
        Route::resource('/users', 'UsersController')->except('show');
        Route::resource('/roles', 'RolesController')->except('show');
        Route::resource('/permissions', 'PermissionsController')->except('show');
        Route::resource('/news', 'NewsController')->except('show');
        Route::resource('/events', 'EventsController')->except('show');
        Route::resource('/forum', 'ForumController')->except('show');
        Route::resource('/glossaries', 'GlossariesController')->except('show');
        Route::resource('/comments', 'CommentsController')->except(['show', 'create', 'store']);
        Route::resource('/bids', 'BidsController')->except(['show', 'create', 'store']);
        Route::resource('/settings', 'SettingsController')->except('show');
        Route::get('/settings/cache-clean', 'SettingsController@cacheClean')->name('settings.cacheClean');

        Route::group(['prefix' => 'survey', 'as' => 'survey.'], function () {
            Route::resource('/questions', 'SurveyQuestionsController')->except('show');
            Route::resource('/factors', 'SurveyFactorsController')->except('show');
            Route::resource('/indicators', 'SurveyIndicatorsController')->except('show');
            Route::resource('/sub-indicators', 'SurveySubIndicatorsController')->except('show');
            Route::resource('/results', 'SurveyResultsController')->only(['index', 'show']);

            Route::get('/indicators/load', 'SurveyIndicatorsController@load')->name('load');
            Route::get('/sub-indicators/load', 'SurveySubIndicatorsController@load')->name('load');
        });
    });
});

routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contacts', 'HomeController@contacts')->name('contacts');

Route::post('/feedback', 'HomeController@feedbackStore')->name('feedback.store');

Route::get('/news', 'NewsController@index')->name('news.index');
Route::get('/news/{slug}', 'NewsController@show')->name('news.show');
Route::get('/events', 'EventsController@index')->name('events.index');
Route::get('/events/{slug}', 'EventsController@show')->name('events.show');
Route::get('/forum', 'ForumController@index')->name('forum.index');
Route::get('/forum/{slug}', 'ForumController@show')->name('forum.show');
Route::get('/wiki', 'GlossariesController@index')->name('glossaries.index');
Route::get('/wiki/{letter}', 'GlossariesController@show')->name('glossaries.show');

Route::get('/comments/load', 'CommentsController@load')->name('comments.load');
Route::post('/comments', 'CommentsController@store')->name('comments.store');

Route::get('/sat', 'SurveyController@index')->name('survey.index');
Route::get('/sat/load-questions', 'SurveyController@loadQuestions')->name('survey.loadQuestions');
Route::post('/sat/result', 'SurveyController@saveResult')->name('survey.saveResult');
Route::get('/sat/result/{uuid}', 'SurveyController@showResult')->name('survey.showResult');

Route::get('/search', 'SearchController@index')->name('search.index');
Route::get('/search/load', 'SearchController@load')->name('search.load');

app/Http/Controllers/SurveyController.php
<?php
namespace App\Http\Controllers;

use App\Http\Resources\SurveyQuestionResource;
use App\Mail\SurveyResultMail;
use App\Models\SurveyQuestion;
use App\Models\SurveyResult;
use App\Services\SurveyService;
use Artesaos\SEOTools\Facades\SEOMeta;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Mail;

class SurveyController extends Controller
{
    private $service;

    public function __construct()
    {
        $this->service = new SurveyService();
    }

    /**
     * List page
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        SEOMeta::setTitle('SAT');

        return view('survey.index');
    }

    /**
     * Save results
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function saveResult(Request $request)
    {
        $uuid         = Str::uuid()->toString();
        $formData     = $request->input('form');
        $userAnswers  = $request->input('answers');
        $factors      = $this->service->getCalculatedFactorsFromAnswers($userAnswers);
        $totalScore   = $this->service->calculateTotalScore($factors);
        $totalFactors = $this->service->calculateTotalFactors($totalScore, $factors);

        SurveyResult::create([
            'uuid'          => $uuid,
            'name'          => $formData['main']['name'],
            'email'         => $formData['main']['email'],
            'affiliation'   => $formData['main']['affiliation'],
            'additional'    => $formData['additional'],
            'answers'       => $userAnswers,
            'total_score'   => $totalScore,
            'total_factors' => $totalFactors,
        ]);

        $emailData = [
            'total_score' => $totalScore,
            'answers'     => $this->service->prepareUserAnswers($userAnswers),
        ];

        try {
            Mail::to($formData['email'])->send(new SurveyResultMail($emailData));
        } catch (\Exception $e) {
            Log::error($e->getMessage());
        }

        return [
            'redirect' => route('survey.showResult', $uuid)
        ];
    }

    /**
     * Save results
     *
     * @param string $uuid
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function showResult(string $uuid)
    {
        $result = SurveyResult::where('uuid', $uuid)->firstOrFail();

        SEOMeta::setTitle('SAT');
        
        return view('survey.result')->with([
            'result' => $result,
        ]);
    }

    /**
     * Load questions
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function loadQuestions()
    {
        $questions = SurveyQuestion::with(['factor', 'indicator', 'subIndicator'])->get();

        return SurveyQuestionResource::collection($questions);
    }
}

resources/views/admin/survey/indicators/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="content content-full bg-body-light">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">Survey Indicators management</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.survey.indicators.index') }}">Questions</a>
                    </li>
                    <li class="breadcrumb-item">Create</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="content">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {{ Form::open(['route' => 'admin.survey.indicators.store', 'files' => true]) }}
                <div class="block">
                    <div class="block-header block-header-default">
                        <div class="block-options">
                            <a href="{{ route('admin.survey.indicators.index') }}" class="btn btn-sm btn-outline-secondary">
                                <i class="fa fa-fw fa-angle-left"></i>
                                Back to list
                            </a>
                        </div>
                        <div class="block-options">
                            <button type="submit" class="btn btn-sm btn-primary btn-save">
                                <i class="fa fa-fw fa-save"></i>
                                Create
                            </button>
                        </div>
                    </div>
                </div>
                @include('admin.survey.indicators.form')
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/survey/indicators/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="content content-full bg-body-light">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Survey Indicators management
                <small class="d-block d-sm-inline-block font-size-base font-w400 text-muted">
                    {{ $indicator->name }}
                </small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.survey.indicators.index') }}">Questions</a>
                    </li>
                    <li class="breadcrumb-item">Edit</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="content">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {{ Form::model($indicator, ['route' => ['admin.survey.indicators.update', $indicator->id], 'method' => 'put']) }}
                <div class="block">
                    <div class="block-header">
                        <div class="block-options">
                            <a href="{{ route('admin.survey.indicators.index') }}" class="btn btn-sm btn-outline-secondary">
                                <i class="fa fa-fw fa-angle-left"></i>
                                Back to list
                            </a>
                        </div>
                        <div class="block-options">
                            <button type="submit" class="btn btn-sm btn-primary btn-save">
                                <i class="fa fa-fw fa-save"></i>
                                Save
                            </button>
                            <button type="button"
                                    class="btn btn-sm btn-alt-danger"
                                    data-action="destroy"
                                    data-destroy-url="{{ route('admin.survey.indicators.destroy', $indicator) }}"
                            >
                                <i class="far fa-fw fa-trash-alt"></i>
                                Delete
                            </button>
                        </div>
                    </div>
                </div>
                @include('admin.survey.indicators.form')
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/survey/indicators/form.blade.php
<div class="block">
    <div class="block-content">
        {{ Form::groupSelect('factor_id', 'Factor', $factors, null, ['placeholder' => 'Select factor...']) }}
        {{ Form::groupText('name', 'Name') }}
        {{ Form::groupText('weight', 'Weight') }}
    </div>
</div>

resources/views/admin/survey/indicators/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="content content-full bg-body-light">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">Survey Indicators management</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">Indicators</li>
                    <li class="breadcrumb-item">List</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="content">
        <a href="{{ route('admin.survey.indicators.create') }}" class="btn btn-primary">
            <i class="fa fa-fw fa-plus mr-1"></i>
            Add indicator
        </a>
    </div>
    <div class="content">
        <div class="block">
            <div class="block-header">
                <h3 class="block-title">Indicators</h3>
            </div>
            <div class="block-content">
                <table class="table table-bordered table-vcenter table-hover">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 50px;">#</th>
                            <th>Name</th>
                            <th>Weight</th>
                            <th>Factor</th>
                            <th style="width: 200px;">Created</th>
                            <th class="text-center" style="width: 100px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($indicators as $indicator)
                            <tr>
                                <th class="text-center">{{ $indicator->id }}</th>
                                <td class="font-w600">{{ $indicator->name }}</td>
                                <td>{{ $indicator->weight }}</td>
                                <td>{{ $indicator->factor->name }}</td>
                                <td>{{ $indicator->created_at }}</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="{{ route('admin.survey.indicators.edit', $indicator) }}" class="btn btn-sm btn-light" data-toggle="tooltip" title="Edit">
                                            <i class="fa fa-fw fa-pencil-alt"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection