routes/admin.php
<?php

Route::group(['prefix' => 'inside', 'as' => 'admin.'], function () {
    Route::group(['prefix' => 'auth'], function () {
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    });

    Route::group(['middleware' => ['auth', 'admin_panel_access']], function () {
        Route::post('ckeditor/upload', 'CkeditorController@upload')->name('ckeditor.upload');

        Route::get('/', 'HomeController@index')->name('home');
        Route::get('/file-manager', 'FilemanagerController@index')->name('fm.index');
        Route::resource('/users', 'UsersController')->except('show');
        Route::resource('/roles', 'RolesController')->except('show');
        Route::resource('/permissions', 'PermissionsController')->except('show');
        Route::resource('/news', 'NewsController')->except('show');
        Route::resource('/events', 'EventsController')->except('show');
        Route::resource('/forum', 'ForumController')->except('show');
        Route::resource('/glossaries', 'GlossariesController')->except('show');
        Route::resource('/comments', 'CommentsController')->except(['show', 'create', 'store']);
        Route::resource('/bids', 'BidsController')->except(['show', 'create', 'store']);
        Route::resource('/settings', 'SettingsController')->except('show');
        Route::get('/settings/cache-clean', 'SettingsController@cacheClean')->name('settings.cacheClean');

        Route::group(['prefix' => 'survey', 'as' => 'survey.'], function () {
            Route::resource('/questions', 'SurveyQuestionsController')->except('show');
            Route::resource('/factors', 'SurveyFactorsController')->except('show');
            Route::resource('/indicators', 'SurveyIndicatorsController')->except('show');
            Route::resource('/sub-indicators', 'SurveySubIndicatorsController')->except('show');
            Route::resource('/results', 'SurveyResultsController')->only(['index', 'show']);

            Route::get('/indicators/load', 'SurveyIndicatorsController@load')->name('load');
            Route::get('/sub-indicators/load', 'SurveySubIndicatorsController@load')->name('load');
        });
    });
});

routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contacts', 'HomeController@contacts')->name('contacts');

Route::post('/feedback', 'HomeController@feedbackStore')->name('feedback.store');

Route::get('/news', 'NewsController@index')->name('news.index');
Route::get('/news/{slug}', 'NewsController@show')->name('news.show');
Route::get('/events', 'EventsController@index')->name('events.index');
Route::get('/events/{slug}', 'EventsController@show')->name('events.show');
Route::get('/forum', 'ForumController@index')->name('forum.index');
Route::get('/forum/{slug}', 'ForumController@show')->name('forum.show');
Route::get('/wiki', 'GlossariesController@index')->name('glossaries.index');
Route::get('/wiki/{letter}', 'GlossariesController@show')->name('glossaries.show');

Route::get('/comments/load', 'CommentsController@load')->name('comments.load');
Route::post('/comments', 'CommentsController@store')->name('comments.store');

Route::get('/sat', 'SurveyController@index')->name('survey.index');
Route::get('/sat/load-questions', 'SurveyController@loadQuestions')->name('survey.loadQuestions');
Route::post('/sat/result', 'SurveyController@saveResult')->name('survey.saveResult');
Route::get('/sat/result/{uuid}', 'SurveyController@showResult')->name('survey.showResult');

Route::get('/search', 'SearchController@index')->name('search.index');
Route::get('/search/load', 'SearchController@load')->name('search.load');

app/Models/ArticleTrait.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Builder;

/**
 * @method \Illuminate\Database\Eloquent\Builder isPublished()
 * @method \Illuminate\Database\Eloquent\Builder search()
 */
trait ArticleTrait
{
    /**
     * Scope: search
     *
     * @param  \Illuminate\Database\Eloquent\Builder $builder
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeSearch(Builder $builder, $searchQuery)
    {
        $builder->where(function ($query) use ($searchQuery) {
            $query->orWhere('title', 'like', '%' . $searchQuery . '%');
            $query->orWhere('content', 'like', '%' . $searchQuery . '%');
        });
    }

    /**
     * Relationship: comments
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    /**
     * Дата публикации в формате Y-m-d
     *
     * @return string
     */
    public function getPublishedDateAttribute(): string
    {
        return $this->published_at->format('Y-m-d');
    }

    /**
     * Increments views count
     *
     * @return bool
     */
    public function incrementViews(): bool
    {
        $this->increment('views');

        return $this->save();
    }

    /**
     * Get commentable title
     *
     * @return string
     */
    public function getCommentableTitle(): string
    {
        return $this->title;
    }

    /**
     * Get commentable type
     *
     * @return string
     */
    public function getCommentableType(): string
    {
        return $this->commentableType;
    }

    /**
     * Get preview image or return default
     *
     * @return string
     */
    public function getPreviewImage(): string
    {
        return $this->preview
            ? asset($this->preview)
            : asset('storage/media/preview_default.png');
    }

    /**
     * Get thumbnail image or return default
     *
     * @return string
     */
    public function getThumbnailImage(): string
    {
        if (!$this->preview) {
            return asset('storage/media/thumbnail_black.png');
        }

        $preview = $this->preview;
        $parts = explode('/preview_', $preview);

        if (count($parts) > 1) {
            return $parts[0] . '/thumbnail_' . $parts[1];
        }

        return $parts[0];
    }
}

app/Models/Forum.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

class Forum extends Model
{
    use HasFactory, ArticleTrait;

    protected $guarded = ['id'];

    protected $casts = [
        'published_at' => 'datetime',
    ];

    protected $commentableType = 'Forum';

    /**
     * Get link to single article page
     *
     * @return string
     */
    public function getPublicLink(): string
    {
        return route('forum.show', $this->slug);
    }

    /**
     * Get link to edit
     *
     * @return string
     */
    public function getEditLink(): string
    {
        return route('admin.forum.edit', $this->id);
    }
}

app/Http/Controllers/Admin/ForumController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ForumRequest;
use App\Models\Forum;
use App\Services\ArticleService;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;

class ForumController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:forums-manage');
    }

    /**
     * Display a listing of the Users.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $forums = Forum::withCount('comments')->latest()->paginate(20);

        return view('admin.forum.index', compact('forums'));
    }

    /**
     * Show the form for creating a new Forum.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function create()
    {
        return view('admin.forum.create');
    }

    /**
     * Store a newly created Forum in storage.
     *
     * @param  \App\Http\Requests\Admin\ForumRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ForumRequest $request)
    {
        $forum = Forum::create([
            'title'        => $request->input('title'),
            'slug'         => $request->input('slug'),
            'is_published' => $request->input('is_published'),
            'published_at' => $request->input('published_at'),
            'excerpt'      => $request->input('excerpt'),
            'content'      => $request->input('content'),
        ]);

        if ($request->hasFile('preview')) {
            $forum->preview = (new ArticleService())->uploadPreviewImage($request->file('preview'), 'forums/' . $forum->id);
        }

        $forum->update();

        return redirect()
            ->route('admin.forum.edit', $forum)
            ->with('success', 'Forum created successfully');
    }

    /**
     * Show the form for editing the specified Forum.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function edit($id)
    {
        $forum = Forum::findOrFail($id);

        return view('admin.forum.edit', compact('forum'));
    }

    /**
     * Update the specified Forum in storage.
     *
     * @param \App\Http\Requests\Admin\ForumRequest $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ForumRequest $request, $id)
    {
        $forum = Forum::findOrFail($id);
        $forum->fill([
            'title'        => $request->input('title'),
            'slug'         => $request->input('slug'),
            'is_published' => $request->input('is_published'),
            'published_at' => $request->input('published_at'),
            'excerpt'      => $request->input('excerpt'),
            'content'      => $request->input('content'),
        ]);

        if ($request->hasFile('preview')) {
            $forum->preview = (new ArticleService())->uploadPreviewImage($request->file('preview'), 'forums/' . $forum->id);
        }

        $forum->update();

        return redirect()
            ->route('admin.forum.edit', $forum)
            ->with('success', 'Forum updated successfully');
    }

    /**
     * Remove the specified Forum from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        File::deleteDirectory(storage_path('public/forums/' . $id));
        Forum::findOrFail($id)->delete();

        if (request()->ajax()) {
            Session::flash('success', 'Forum article deleted successfull');

            return response()->json(['success' => true, 'redirect' => route('admin.forum.index')]);
        } else {
            return redirect()
                ->route('admin.forum.index')
                ->with('success','Forum article deleted successfully');
        }
    }
}

app/Http/Controllers/ForumController.php
<?php
namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Forum;
use Artesaos\SEOTools\Facades\SEOMeta;
use Illuminate\Http\Request;

class ForumController extends Controller
{
    /**
     * List page
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Contracts\Support\Renderable|array
     */
    public function index(Request $request)
    {
        $articles = Forum::isPublished();

        if ($request->get('order') === 'popular') {
            $articles = $articles->orderByDesc('views')->latest();
        } else {
            $articles = $articles->latest();
        }

        $articles = $articles->paginate(6);

        if ($request->ajax()) {
            return [
                'html'        => view('forum.articles-list', compact('articles'))->render(),
                'total'       => $articles->total(),
                'currentPage' => $articles->currentPage(),
                'lastPage'    => $articles->lastPage(),
            ];
        }

        SEOMeta::setTitle('Forum');

        return view('forum.index')->with([
            'forums' => $articles
        ]);
    }

    /**
     * Article page
     *
     * @param string $slug
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function show($slug)
    {
        $article  = Forum::where('slug', $slug)->isPublished()->firstOrFail();
        $comments = Comment::for($article)
            ->isPublished()
            ->latest()
            ->paginate(3);

        $relatedArticles = Forum::isPublished()
            ->where('id', '!=', $article->id)
            ->inRandomOrder()
            ->limit(2)
            ->get();

        $article->incrementViews();

        SEOMeta::setTitle($article->title);

        if ($article->excerpt) {
            SEOMeta::setDescription($article->excerpt);
        }

        return view('forum.show')->with([
            'article'         => $article,
            'comments'        => $comments,
            'relatedArticles' => $relatedArticles,
        ]);
    }
}

resources/views/admin/forum/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="content content-full bg-body-light">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">Forums management</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.forum.index') }}">Forums</a>
                    </li>
                    <li class="breadcrumb-item">Create</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="content">
        {{ Form::open(['route' => 'admin.forum.store', 'files' => true]) }}
        <div class="block">
            <div class="block-header block-header-default">
                <div class="block-options">
                    <a href="{{ route('admin.forum.index') }}" class="btn btn-sm btn-outline-secondary">
                        <i class="fa fa-fw fa-angle-left"></i>
                        Back to list
                    </a>
                </div>
                <div class="block-options">
                    <button type="submit" class="btn btn-sm btn-primary btn-save">
                        <i class="fa fa-fw fa-save"></i>
                        Create
                    </button>
                </div>
            </div>
        </div>
        @include('admin.forum.form')
        {{ Form::close() }}
    </div>
@endsection

resources/views/admin/forum/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="content content-full bg-body-light">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Forums management
                <small class="d-block d-sm-inline-block font-size-base font-w400 text-muted">
                    {{ $forum->title }}
                </small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.forum.index') }}">Forums</a>
                    </li>
                    <li class="breadcrumb-item">Edit</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="content">
        {{ Form::model($forum, ['route' => ['admin.forum.update', $forum->id], 'method' => 'put', 'files' => true]) }}
        <div class="block">
            <div class="block-header">
                <div class="block-options">
                    <a href="{{ route('admin.forum.index') }}" class="btn btn-sm btn-outline-secondary">
                        <i class="fa fa-fw fa-angle-left"></i>
                        Back to list
                    </a>
                </div>
                <div class="block-options">
                    <button type="submit" class="btn btn-sm btn-primary btn-save">
                        <i class="fa fa-fw fa-save"></i>
                        Save
                    </button>
                    <button type="button"
                            class="btn btn-sm btn-alt-danger"
                            data-action="destroy"
                            data-destroy-url="{{ route('admin.forum.destroy', $forum) }}"
                    >
                        <i class="far fa-fw fa-trash-alt"></i>
                        Delete
                    </button>
                </div>
            </div>
        </div>
        @include('admin.forum.form')
        {{ Form::close() }}
    </div>
@endsection

resources/views/admin/forum/form.blade.php
<div class="row">
    <div class="col-sm-8">
        <div class="block">
            <div class="block-content">
                {{ Form::groupText('title', 'Title') }}
                {{ Form::groupTextarea('excerpt', 'Excerpt', null, ['rows' => 3]) }}
                {{ Form::groupTextarea('content', 'Content', null, ['id' => 'ckeditor-full']) }}
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="block">
            <div class="block-content">
                {{ Form::groupSwitch('is_published', 'Published', '1', null, ['id' => 'is_published', 'switch-size' => 'lg']) }}
                {{ Form::groupDate('published_at', 'Published date', null, ['data-date-format' => 'Y-m-d']) }}
                {{ Form::groupText('slug', 'Slug (URL)') }}
                {{ Form::groupPreview('preview', 'Preview', ['accept' => 'image/*', 'hint' => 'min-width=600px, min-height=470px']) }}
                {{ Form::groupText('views', 'Views Count', null, ['readonly' => 'readonly']) }}
            </div>
        </div>
    </div>
</div>
@push('styles')
    <link rel="stylesheet" href="{{ asset('admin/js/plugins/flatpickr/flatpickr.min.css') }}">
@endpush

@push('scripts')
    <script src="{{ asset('admin/js/plugins/flatpickr/flatpickr.min.js') }}"></script>
    <script src="{{ asset('admin/js/plugins/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script>
    <script>
        jQuery(function () {
            One.helpers([
                'flatpickr',
            ]);
        });
    </script>
@endpush

resources/views/admin/forum/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="content content-full bg-body-light">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">Forums management</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">Forums</li>
                    <li class="breadcrumb-item">List</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="content">
        <a href="{{ route('admin.forum.create') }}" class="btn btn-primary">
            <i class="fa fa-fw fa-plus mr-1"></i>
            Add article
        </a>
    </div>
    <div class="content">
        <div class="block">
            <div class="block-header">
                <h3 class="block-title">Forums</h3>
            </div>
            <div class="block-content">
                <table class="table table-bordered table-vcenter table-hover">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 50px;">#</th>
                            <th>Title</th>
                            <th>slug</th>
                            <th>Comments</th>
                            <th style="width: 200px;">Published</th>
                            <th style="width: 200px;">Published Date</th>
                            <th class="text-center" style="width: 100px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($forums as $forum)
                            <tr>
                                <th class="text-center">{{ $forum->id }}</th>
                                <td class="font-w600">{{ $forum->title }}</td>
                                <td>{{ $forum->slug }}</td>
                                <td>{{ $forum->comments_count }}</td>
                                <td>{!! $forum->getIsPublishedBadge() !!}</td>
                                <td>{{ $forum->published_date }}</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="{{ route('admin.forum.edit', $forum) }}" class="btn btn-sm btn-light" data-toggle="tooltip" title="Edit">
                                            <i class="fa fa-fw fa-pencil-alt"></i>
                                        </a>
                                        <a href="{{ route('admin.comments.index', ['id' => $forum->id, 'type' => 'forum']) }}" class="btn btn-sm btn-light" data-toggle="tooltip" title="Comments">
                                            <i class="far fa-comment-alt"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $forums->links() }}
            </div>
        </div>
    </div>
@endsection